### ISSUE TITLE
Hera 5.1.7 start errors

### ISSUE THREAD

**Issue by thomas-shirley** [markstory/gala-alt-tab-plus#10]
**Hera 5.1.7 Launch Failure**

Compiles and installs without a hitch, but throws an 'unsupported session type' on gala --replace &

I don't have a 5.1.6 iso to check whether the problem is specific to the 5.1.7 build :(

![Screenshot from 2021-01-08 18 07 28](https://user-images.githubusercontent.com/5425280/104049215-802cb280-51dc-11eb-809c-19cfddfcdf68.png)

**Comment by markstory** [comment]
Does the application switcher work though? I don't think that warning is coming from this plugin.

**Comment by thomas-shirley** [comment]
Yep, the switcher still fires. Strange. I'll give it a try on a fresh VM install to see if I can reproduce.

**Comment by thomas-shirley** [comment]
Fresh install of 5.1.7. Alt+Shift keybind disabled, compiled successfully.

https://user-images.githubusercontent.com/5425280/104067154-8df13080-51fa-11eb-9597-88e7f398cb53.mp4

Still no dice. Tried on bare metal and in a VM. Anything I can include to help with debugging?

**Comment by thomas-shirley** [comment]
Got it. Looks like the plugin isn't being copied to the correct path. It should be:

/usr/lib/x86_64-linux-gnu/gala/plugins

The CMakeLists.txt destination is:

lib/x86_64-linux-gnu/gala/plugins

The plugin works a treat when the libgala-alt-tab-plus.so is copied across manually or the CMakeLists.txt is updated to include the full destination path:

install(TARGETS ${NAME} DESTINATION /usr/lib/x86_64-linux-gnu/gala/plugins)

**Comment by markstory** [comment]
Whoops. I had fixed the path but forgot to push the commit. Fixed in 556dbba9003c7b42ff7dc2e5bed6de52167e5ba9
